### PR TITLE
Fixing logo issue

### LINKED ISSUE #66: Adding logo has no effet
**Version**: 1.5.4
**Description**:
Adding a logo in the customization menu has no effect (the logo is not displayed anywhere on the page)

### PR DESCRIPTION
**Pull request by victorperin**
Also removing select "Display as", now it's automatic.
Fixes #66

### CODE REVIEW

**Comment by thanhluu** [comment]
Hi @victorperin : How can I using Logo Image only?

**Comment by victorperin** [comment]
You just need to clear the title. When you do that, the script will recignize that you're not using it and assume that you'll use just the logo
Sent using CloudMagic
On dom, fev 15, 2015 at 2:28 PM, Thanh Luu <notifications@github.com> wrote:Hi @victorperin : How can I using Logo Image only?

**Comment by victorperin** [comment]
I found an error when I tested on mobile. This was before my changes, too.
I quickly fixed it with just a <br /> tag.

**Comment by thanhluu** [comment]
I think we should not use that solution. Leave Site Title blank is not good for SEO.

**Comment by victorperin** [comment]
Alright, so I think this button must be most simple to use.

**Comment by thanhluu** [comment]
@victorperin can you check this pull request. It can't be merged.

**Pull request closed without merging**
